name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: divyansh1502
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: snake.svg

      - name: Commit snake.svg if it exists
        run: |
          if [ -f snake.svg ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add snake.svg
            git commit -m "Update snake.svg"
            git push
          else
            echo "snake.svg not found, skipping commit"
          fi
